### ISSUE TITLE
M6: Read Rat Information, Robustness, Diagrams, Architecture, and UI Prototypes

### ISSUE THREAD

**Issue by cathy-liu23** [Jason27chan/Ratatouille#19]
1) Create Robustness Diagram
2) Create architecture diagram [annotate trust boundaries]
3) Create UI flow diagram
4) Prototype (sketches) or major screens
5) Implement ability to read rat reporting data
6) Store data in model
7) Provide list view of data

**Comment by jasmliu** [comment]
RecyclerView
AsyncTask
